name: app-client-web
region: sfo
static_sites:
  - build_command: npm run build
    environment_slug: node-js
    github:
      branch: main
      deploy_on_push: true
      repo: intrepion/code-sample-client-for-lifelogic
    name: client-web
    routes:
      - path: /
    source_dir: /
